create table animals (
    animal_id integer primary key generated by default as identity,
    animal_type text default null,
    animal_description text default null,
    belongs_to_pid text default null
);